* LACP restart
  * LACP
    * Micro BFD configuration.
      * Wait for LACP to be up.
        * LACP adds interface to active list.
        * All member links in active list programmed in hardware.
      * BFD goes down
        * reset LACP, and remove member link from active member list.
        * wait for LACP to come up, if LACP comes up and LACP is up add back the member links to the list.
        * if LACP times out.
          * we dont have to add back.
      * Software BFD + TILFA doesnt make sense:
        * Code flow remains the same, no change.
  * static
    * by default link is active list until otherwise LINK DOWN.
    * if BFD goes down, we have to mark the interface egress disable.
    * But we would receive link down before egress disable, so we will automatically remove from the active list.
      * how would TILFA handle this, there is link down and BFD down notifications.
        * we would receive Link down first and if appropriate switch to protected bond.
        * if we receive BFD down we still mark member link egress disabled
    * incase of link down we would be considering LINK_DOWN and BFD admin down the same way ?
    * BFD down is egress disabled + 1
    * LINK down is active - 1.
    * But the Math works out to be the same.
    * if act_cnt - egress_disable < min_links then switch over.

  * TILFA
    * Any down notification from DPAL will be first handled by TILFA.
    * any new down notification, check if its already in egress disabled list.
    * egress disable from DPAL, but then we have to write OAM object.
      * We could also not change anything in the LIST and just mark it egress disabled.
      * PI worker thread notification would come and this time it will move it to egress disable list.
        * So it becomes important that we dont miss any egress disable list notification from worker thread.
          * If not the interface will continue to be in egress disable until otherwise
      * Once we receive egress enable in DPAL we again enable it.
    * if act_cnt - egress_disable < min_links then switch over.
